### ISSUE TITLE
Error in HSCIC calculation

### ISSUE THREAD

**Issue by yichengleo** [namratadeka/circe#1]
https://github.com/namratadeka/circe/blob/07648726785337582dd08f693e1567eab8d9a8ff/utils/losses.py#L81
In the HSCIC calculation function, I identified an error that led to unreasonable outcomes in my research.
Upon inspection, I recommend modifying the following line.
```     
WtKyy = torch.linalg.solve(Ky + ridge_lambda  * torch.eye(Ky.shape[0]).to(Ky.device), Kx)
```
given the equation in the paper as following.
![image](https://github.com/namratadeka/circe/assets/129526128/d3eb6101-c308-4d19-be3f-c3cc233395c6)

**Comment by romanpogodin** [comment]
Thanks for the comment! I think our computation is correct, but it doesn't use the exact solution you attached.

 [We use this paper's](https://proceedings.neurips.cc/paper/2020/file/f340f1b1f65b6df5b5e3f94d95b11daf-Paper.pdf) (the same one as in your screenshot) definition of W:

<img width="667" alt="image" src="https://github.com/namratadeka/circe/assets/11966916/02537374-2643-4c62-8180-a40928382ff8">

It is then always used with the Ky kernel (not Kz since we have X ind. Z | Y and not X ind. Y | Z like in the HSCIC paper) to compute HSCIC as follows:  
<img width="667" alt="image" src="https://github.com/namratadeka/circe/assets/11966916/fa24978a-2f24-430c-931f-e5c4ff9c5fa8">

Perhaps the change of notation (conditioning on Y rather than Z) led to some confusion?

**Comment by romanpogodin** [comment]
The issue seems to be resolved, so I'm closing it.
